# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Akyos\FormBundle\:
        resource: './../../*'
        tags: ['controller.service_arguments']
        public: true

    form.sidebar:
        alias: "Akyos\\FormBundle\\Service\\ExtendSidebar"
        public: true

    form.form:
        alias: "Akyos\\FormBundle\\Service\\Form"
        public: true
